### ISSUE TITLE
Getting org.ghost4j.GhostscriptException: Cannot initialize Ghostscript interpreter. Error code is -13

### ISSUE THREAD

**Issue by mananshah88** [zippy1978/ghost4j#62]
Hi, 
I am facing a weird problem. My code works on my machine but not on production. :D :D :D 

Ghostscript: 9.18 (2015-10-05) 
Ghostscript4j : 1.0.1
jna: 4.1.0
( all versions are same on local machine as well as on production.) 

I am trying to create thumbnail from the PDF file.

Here is my code: 

```
Ghostscript gs = Ghostscript.getInstance();
String[] gsArgs = new String[11];
gsArgs[1] = "-sDEVICE=png16m";
gsArgs[2] = "-dPDFFitPage=true";
gsArgs[3] = "-dDEVICEWIDTHPOINTS=680";
gsArgs[4] = "-dDEVICEHEIGHTPOINTS=480";
gsArgs[5] = "-dBATCH";
gsArgs[6] = "-dNOPAUSE";
gsArgs[7] = "-dNOPROMPT";
gsArgs[8] = "-dQUIET";
gsArgs[9] = "-sOutputFile=some_file_name";
gsArgs[10] = "some_input_file_name";

try {
	gs.initialize(gsArgs);
	gs.exit();
} catch (GhostscriptException e) {
	e.printStackTrace();
}

```
The error I got on my production is: 

```
org.ghost4j.GhostscriptException: Cannot initialize Ghostscript interpreter. Error code is -13
	at org.ghost4j.Ghostscript.initialize(Ghostscript.java:365)
        .....
org.ghost4j.GhostscriptException: Cannot initialize Ghostscript interpreter. Error code is -13
```

Can anyone gives me any direction?

**Comment by 4F2E4A2E** [comment]
GS can not be initialize, on production only you say? 
Everything installed and permissions set?

**Comment by mananshah88** [comment]
Thanks 4F2E4A2E, for the quick response.

Yup... it seems everything installed perfect.
( Note: I have installed it by 'sudo apt install ghostscript' . So i guess permission would not be an issue.)

Is there any way to verify this?

By the way, 
If i execute command from terminal 
`gs -sDEVICE=png16m -dPDFFitPage=true -dDEVICEWIDTHPOINTS=680 -dDEVICEHEIGHTPOINTS=480 -dBATCH -dNOPAUSE -dNOPROMPT -dQUIET -sOutputFile=filename some_input_file.pdf`

it would generate thumbnail properly.

**Comment by 4F2E4A2E** [comment]
What about the permission of the application you’re running?

**Comment by mananshah88** [comment]
It has same access level.  'sudo'

**Comment by kvadlamani** [comment]
@mananshah88 Could you please let us know how you've enabled debug mode in Ghost4j? I am getting the same exception "Cannot initialize Ghostscript interpreter". But the Error code is -15 instead of -100. I am setting parameters for debugging but it doesn't seem to work. Thanks in advance.

**Comment by mananshah88** [comment]
@kvadlamani  sorry its a very old thread. So i do not remember exactly.  
But there are parameters like "-dPDFDEBUG, -dPDFWRDEBUG" which could help you.

There are others as well. You can get it from here: https://www.ghostscript.com/doc/current/Use.htm#Environment_variables (13. Debugging section)

**Comment by kvadlamani** [comment]
@mananshah88 Thanks for the reply. Unfortunately, none of the debug options worked for me. This is the code I am trying to execute:

`public static void main(String[] args) throws GhostscriptException {
		final Ghostscript gs = Ghostscript.getInstance();
		final String basePath = "/usr/local/downloads/";
		final String fileName = "xyz";
		final String[] gsArgs = getArgs(basePath, fileName);
		gs.initialize(gsArgs);

	}

	private static String[] getArgs(String basePath, String fileName) {
		final ArrayList<String> args = new ArrayList<String>();
		args.add("-sDEVICE=pdfwrite");
		args.add("-dPDFX");
		args.add("-dBATCH");
		args.add("-dNOPAUSE");
		args.add("-dNOOUTERSAVE");
		args.add("-sProcessColorModel=DeviceCMYK");
		args.add("-dUsePDFX3Profile");
		args.add("-sOutputFile=" + basePath + fileName + "-x1a.pdf");
		args.add(basePath + "PDFX1A_def.ps");
		args.add(basePath + fileName + ".pdf");
		return args.toArray(new String[0]);
	}` 

and I am getting the exception:

`Exception in thread "main" org.ghost4j.GhostscriptException: Cannot initialize Ghostscript interpreter. Error code is -15
	at org.ghost4j.Ghostscript.initialize(Ghostscript.java:365)
	at com.testing.DisplayCallbackExample.main(DisplayCallbackExample.java:24)
`
